// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Method               *int64   `protobuf:"varint,1,req,name=method" json:"method,omitempty"`
	Logid                *int64   `protobuf:"varint,2,req,name=logid" json:"logid,omitempty"`
	Params               *string  `protobuf:"bytes,3,opt,name=params" json:"params,omitempty"`
	Type                 *int32   `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_2e0f6dc4be7ca0d4, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMethod() int64 {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return 0
}

func (m *Message) GetLogid() int64 {
	if m != nil && m.Logid != nil {
		return *m.Logid
	}
	return 0
}

func (m *Message) GetParams() string {
	if m != nil && m.Params != nil {
		return *m.Params
	}
	return ""
}

func (m *Message) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_2e0f6dc4be7ca0d4) }

var fileDescriptor_message_2e0f6dc4be7ca0d4 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe3, 0x62, 0xf7, 0x85, 0x08,
	0x08, 0xf1, 0x71, 0xb1, 0xe5, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x48, 0x30, 0x2a, 0x30, 0x69, 0x30,
	0x0b, 0xf1, 0x72, 0xb1, 0xe6, 0xe4, 0xa7, 0x67, 0xa6, 0x48, 0x30, 0x81, 0xb9, 0x7c, 0x5c, 0x6c,
	0x05, 0x89, 0x45, 0x89, 0xb9, 0xc5, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x42, 0x3c, 0x5c, 0x2c,
	0x25, 0x95, 0x05, 0xa9, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xac, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2a, 0x0f, 0x00, 0xdd, 0x57, 0x00, 0x00, 0x00,
}
